FROM python:3.10-slim

WORKDIR /app

COPY ./ /app

RUN pip install --progress-bar off --no-cache-dir --upgrade -r /app/requirements.txt

EXPOSE 14358

HEALTHCHECK CMD curl --fail http://localhost:14358/_stcore/health

ENTRYPOINT ["streamlit", "run", "/app/mturk_explanations_study_main.py", "--server.port=14358", "--server.address=0.0.0.0"]