FROM python:3.10-slim

WORKDIR /mturk-explanation-study

COPY ./ /mturk-explanation-study

RUN pip install --progress-bar off --no-cache-dir --upgrade -r /mturk-explanation-study/requirements.txt

EXPOSE 14358

HEALTHCHECK CMD curl --fail http://localhost:14358/mturk-explanation-study/_stcore/health

ENTRYPOINT ["streamlit", "run", "/mturk-explanation-study/mturk_explanations_study_main.py", "--server.port=14358", "--server.address=0.0.0.0"]